# Generated by Django 5.2.7 on 2026-03-08 17:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Doctor's contact number", max_length=20
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Medical specialization (e.g., General Practitioner, Cardiologist)",
                        max_length=255,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, help_text="Medical license number", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Screening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Patient's full name for identification",
                        max_length=255,
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        help_text="Patient age in years",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        help_text="Patient gender (Male/Female)",
                        max_length=10,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for follow-up",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address (optional)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight in kilograms",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "systolic_bp",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Systolic blood pressure (top number) in mmHg",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "diastolic_bp",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Diastolic blood pressure (bottom number) in mmHg",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(150),
                        ],
                    ),
                ),
                (
                    "glucose_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Blood glucose level in mg/dL",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "heart_rate",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Heart rate in BPM",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(220),
                        ],
                    ),
                ),
                (
                    "known_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Known conditions (e.g., Diabetes, Hypertension)",
                        null=True,
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(
                        blank=True,
                        help_text="Current medications the patient is taking",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or observations",
                        null=True,
                    ),
                ),
                (
                    "screened_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of the volunteer who performed the screening",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "doctor_advice",
                    models.TextField(
                        blank=True,
                        help_text="Doctor's clinical impressions and recommended actions",
                        null=True,
                    ),
                ),
                (
                    "consultation_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the doctor provided consultation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Doctor who provided consultation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="screenings.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Screenings",
                "ordering": ["-created_at"],
            },
        ),
    ]
