# Generated by Django 5.2.7 on 2026-03-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screenings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="screening",
            name="requires_specialist_followup",
            field=models.BooleanField(
                default=False,
                help_text="Whether the patient requires specialist follow-up",
            ),
        ),
    ]
