# Generated by Django 4.2.7 on 2026-09-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("screenings", "0002_screening_requires_specialist_followup"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_id",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., #A-104",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("patient_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "is_urgent",
                    models.BooleanField(
                        default=False, help_text="Flagged for emergency triage"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Marked True after final discharge"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        help_text="e.g., Vitals Intake, Optometry, General Consult",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "schema",
                    models.JSONField(
                        default=list,
                        help_text="List of field definitions for form rendering",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["role_name"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Table 1: Registration, Table 2: Blood Pressure",
                        max_length=100,
                    ),
                ),
                (
                    "step_order",
                    models.PositiveIntegerField(
                        help_text="Order in the workflow (1, 2, 3...)"
                    ),
                ),
                (
                    "is_final_discharge",
                    models.BooleanField(
                        default=False,
                        help_text="Mark True if this is the Admin Discharge table",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role_config",
                    models.ForeignKey(
                        help_text="Schema used at this station",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="screenings.roleconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Screening Station",
                "verbose_name_plural": "Screening Stations",
                "ordering": ["step_order"],
            },
        ),
        migrations.CreateModel(
            name="StationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Data key-value pairs captured at this specific station",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional comments or clinical observations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_entries",
                        to="screenings.patientworkflow",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="screenings.screeningstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station Entry",
                "verbose_name_plural": "Station Entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="screening",
            name="doctor",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Screening",
        ),
        migrations.AddField(
            model_name="patientworkflow",
            name="current_station",
            field=models.ForeignKey(
                blank=True,
                help_text="The station where the patient is currently waiting or being served",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waiting_patients",
                to="screenings.screeningstation",
            ),
        ),
    ]
