# Generated by Django 4.2.7 on 2026-09-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screenings", "0003_patientworkflow_roleconfig_screeningstation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientworkflow",
            name="is_discharged",
            field=models.BooleanField(
                default=False,
                help_text="Locked after admin discharge; prevents post-exit edits",
            ),
        ),
        migrations.AddField(
            model_name="screeningstation",
            name="station_type",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Table 1: Registration"),
                    ("VITALS", "Table 2: Vitals"),
                    ("DOCTOR_TRIAGE", "Table 3A: Doctor Triage"),
                    ("LAB_GLUCOSE", "Table 3B: Lab / Glucose"),
                    ("DISCHARGE", "Table 4: Admin Discharge"),
                    ("GENERAL", "General Checkout"),
                ],
                default="GENERAL",
                help_text="Functional type for routing logic",
                max_length=30,
            ),
        ),
    ]
