# Generated by Django 4.2.7 on 2026-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screenings", "0004_patientworkflow_is_discharged_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="patientworkflow",
            index=models.Index(
                fields=["is_completed", "is_discharged", "-created_at"],
                name="screenings__is_comp_b19d73_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientworkflow",
            index=models.Index(
                fields=["current_station", "is_completed"],
                name="screenings__current_f2d27d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="screeningstation",
            index=models.Index(
                fields=["station_type", "is_active"],
                name="screenings__station_fee5a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="screeningstation",
            index=models.Index(
                fields=["step_order"], name="screenings__step_or_ce77ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stationentry",
            index=models.Index(
                fields=["station", "created_at"], name="screenings__station_4fc2fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stationentry",
            index=models.Index(
                fields=["patient", "station"], name="screenings__patient_eb7dbe_idx"
            ),
        ),
    ]
