# Generated by Django 4.2.7 on 2026-09-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screenings", "0005_patientworkflow_screenings__is_comp_b19d73_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationentry",
            name="client_submission_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Client-generated idempotency key for offline sync deduplication",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stationentry",
            unique_together={("patient", "station", "client_submission_id")},
        ),
        migrations.AddIndex(
            model_name="stationentry",
            index=models.Index(
                fields=["client_submission_id"], name="screenings__client__93e144_idx"
            ),
        ),
    ]
