# Generated by Django 4.2.7 on 2026-09-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screenings", "0006_stationentry_client_submission_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stationentry",
            name="client_submission_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Client-generated idempotency key for offline sync deduplication",
                max_length=100,
            ),
        ),
    ]
